baseURL: "https://saimadhu27.github.io/portfolio/"
languageCode: "en-us"
title: "Madhuri"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
  #  - identifier: blog
  #    name: Blog
  #    title: Blog posts
  #    url: /blogs
  #    weight: 1
  #  - identifier: gallery
  #    name: Gallery
  #    title: Blog posts
  #    url: /gallery
  #    weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
#  title: "Madhuri"
#  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
#  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
#  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    #align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
  #  brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
  #  disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Sai Madhuri Kandula."
    #subtitle: "I build things for the web"
    content: "A passionate Data Science Graduate Student who loves using data to build stories and enhance products.I love travelling and I live in Tucson, AZ"
    image: /images/me1.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://docs.google.com/document/d/1OlutQ1TF7j4YvCDWs7M_puzXEQB4IjdeTquOZ5UPkpI/edit"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/saimadhu27
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/sai-madhuri-kandula/
      #customIcons:
      #  - icon: /fav.png
      #    url: "https://example.com"

  # About
  about:
    enable: true
    title: "About me"
    image: "/images/me.png"
    content: |-
      My academic journey equipped me with a solid grasp of statistical concepts, data manipulation, and hypothesis testing. I am proficient in statistical programming languages like R and Python, enabling me to extract valuable insights from data and derive meaningful conclusions. My coursework has honed my skills in regression analysis, and NLP which I am eager to apply to practical scenarios.
      Curiosity is my driving force, and I am enthusiastic about diving into data sets to uncover hidden patterns and trends. I am excited to leverage my analytical prowess to contribute to projects that drive informed decision-making and business growth. Whether it's exploring data, building predictive models, or crafting compelling visualizations, I am committed to delivering actionable insights that make a tangible impact.
    skills:
      enable: true
      title: ""
      items:
        - "Python, R, SQL, Sci-Kit Learn, Tableau"
        - "Multi-Cultural Fluency, Team Player"


  # Experience
  experience:
    enable: true
     #title: "Custom Name"
    items:

      - job: "Associate Software Engineer"
        company: "Eviga Inc."
        companyUrl: "https://Eviga.com"
        date: "Sep 2022 - Dec 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          #content: I worked as a software developer for more than one year in Amazon.
        content: |
          - Worked on data collation and harmonisation of the customer data
          - To get a unified view of the customer data using Informatica IDQ and Salesforce

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Masters in Data Science"
        school:
          name: "University of Arizona, Tucson"
          #url: "https://example.org"
        date: "Jan 2023 - Jan 2025"
        GPA: "4.0 out of 4.0"
        content: |-
          Relevant Coursework
            - Machine Learning, Natural Language Processing, Data mining
            - Data Visualisation, Neural Networks, SQL/No SQL Databases
      - title: "Bachelor of Science in Statistics"
        school:
          name: "Lady Shri Ram College for Women, University of Delhi"
          #url: "https://example.org"
        date: "2018 - 2021"
        GPA: "9.203 out of 10"
        content: |-
          Relevant Coursework
          - Linear Models, Statistical Inference, Multivariate Analysis and Nonparametric Methods
          - Survival Analysis and BioStatistics, Financial Statistics



  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Fake News Detection - NLP
        content: Developed an Machine Learning Algorithm to detect fake news articles with the help of Natural Language Processing.
        image: /images/projects/f1.jpg
        featured:
          name: Click here to read more!
          link: https://github.com/saimadhu27/FakeNews_Detection_NLP
        #badges:
        #  - "Hugo"
        #  - "Bootstrap"
        #  - "Javascript"
        #links:
        #  - icon: fab fa-github
        #    url: https://github.com/saimadhu27/FakeNews_Detection_NLP


      - title: Maximizing Bank Marketing Efficiency with Machine Learning Techniques
        content: Analyzed the data and developed a Machine Learning model to predict if the customer will subscribe to the term deposit and found the features that influence the bank marketing campaign more.
        image: /images/projects/profile2.jpg
        featured:
          name: Click here to know more!
          link: https://github.com/saimadhu27/ML_model_for_Bank_Marketing
      #  badges:
      #    - "Django"
      #    - "Bootstrap"
      #  links:
      #    - icon: fab fa-github
      #      url: https://github.com/gurusabarish/converter



      - title: Customer Insights Analysis - Uncovering Patterns and Trends through Statistical Analysis
        content: Digging through data and finding significant insights to advertise better products to customers of different backgrounds.
        image: /images/projects/converter.jpg
        featured:
          name: Click here to know more!
          link: https://github.com/saimadhu27/Statistics_project
      #  badges:
      #     - "Hugo"
        #  - "Bootstrap"
        #  - "Javascript"
        #links:
        #  - icon: fab fa-github
        #    url: https://github.com/gurusabarish/HugoProfileV2


  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: National Merit Scholarship
        content: Received National Merit Scholarship in College which is only awarded to top 12% students in each state.
        #url: https://example.com
        #image: /images/achievment.jpg



  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: saimadhurikandula@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/saimadhu27
      linkedin: https://www.linkedin.com/in/sai-madhuri-kandula/
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"


  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
